--- # Hyperparameters for grid searching different scikit-learn classifiers
ProblemType: 'Classification'
CV: 5
ParallelJobs: -1
Scoring: 'f1_micro' # Must be in sorted(sklearn.metrics.SCORERS.keys())
Hyperparameters:
  SVC:
    kernel: ['rbf']
    gamma: ['scale']
    C: [0.01, 0.1]
    max_iter: [100]
  RandomForestClassifier:
    n_estimators: [250, 500]
    criterion: ['entropy', 'gini']
    max_features: ['sqrt']
